const views=document.querySelectorAll('.view');const nav=document.querySelectorAll('nav button');const toast=document.querySelector('.toast');
function go(id){views.forEach(v=>v.classList.toggle('active',v.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
function pop(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2300)}
const voiceModal=document.querySelector('#voiceModal');const reportModal=document.querySelector('#reportModal');
function open(m){m.classList.add('open');m.setAttribute('aria-hidden','false')}function close(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}
document.querySelector('#voice').onclick=()=>open(voiceModal);document.querySelector('#previewReport').onclick=()=>open(reportModal);document.querySelector('#finish').onclick=()=>open(reportModal);document.querySelectorAll('.close').forEach(x=>x.onclick=()=>close(x.closest('.modal')));
document.querySelector('#record').onclick=()=>{const btn=document.querySelector('#record'),dot=document.querySelector('#micDot');btn.textContent='Sto ascoltando…';dot.parentElement.classList.add('recording');setTimeout(()=>{btn.style.display='none';dot.parentElement.classList.remove('recording');document.querySelector('#voiceTitle').textContent='Ho capito questo';document.querySelector('#voiceHint').textContent='Controlla gli alimenti e le quantità prima di salvare.';document.querySelector('#transcript').hidden=false},1100)};
document.querySelector('#confirmFood').onclick=()=>{close(voiceModal);pop('Pasto salvato nel diario di Anna')};document.querySelector('#manual').onclick=()=>pop('Apertura inserimento manuale');document.querySelector('#sendFood').onclick=()=>pop('Report alimentare inviato ad Anna');document.querySelector('#sendWorkout').onclick=()=>{close(reportModal);pop('Report allenamento inviato a Luca')};document.querySelector('#share').onclick=()=>pop('Report mensile inviato al tuo team');document.querySelectorAll('.set-btn').forEach(b=>b.onclick=()=>pop('Serie registrata · record aggiornati'));
document.querySelector('#newMealPlan').onclick=()=>pop('Nuova scheda nutrizionale creata');document.querySelector('#duplicatePlan').onclick=()=>pop('Piano duplicato nella libreria');document.querySelector('#nutritionToPt').onclick=()=>pop('Sintesi alimentazione inviata a Luca');document.querySelector('#newTrainingPlan').onclick=()=>pop('Nuova scheda allenamento creata');document.querySelector('#assignPlan').onclick=()=>pop('Scheda assegnata a Sofia');document.querySelector('#trainingToNutrition').onclick=()=>pop('Sintesi allenamenti inviata ad Anna');document.querySelector('#changePeriod').onclick=()=>pop('Confronto periodo aggiornato');
